language: node_js

jobs:
  include:
    - os: linux
      dist: xenial
    - os: linux
      dist: trusty
    - os: linux
      dist: bionic
    - os: osx
      osx_image: xcode7.2

node_js:
  - 10

cache:
  directories:
  - "$HOME/.npm"

