name: Node.js CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
        node-version: [14.x, 16.x, 18.x]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install MacOS system deps
        if: ${{matrix.platform == 'macos-latest'}}
        run: brew update && brew install pkg-config cmake glib gcovr
      - name: Install Ubuntu system deps
        if: ${{matrix.platform == 'ubuntu-latest'}}
        run: sudo apt update && sudo apt -y install gcovr
      - run: npm ci
      - run: npm test
      - run: npm run build-debug
      - run: NODE_ENV=development npm test
      - run: ctest --test-dir build -VV
        env:
          CI: true
