name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, ubuntu-22.04, macos-latest]
        node-version: [20.x, 22.x, 24.x]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install MacOS system deps
        if: ${{contains(matrix.platform, 'macos') }}
        run: brew update && brew install pkg-config cmake glib gcovr
      - name: Install Ubuntu system deps
        if: ${{contains(matrix.platform, 'ubuntu') }}
        run: sudo apt update && sudo apt -y install gcovr
      - run: ./test/test.sh
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
         gcov: true
         verbose: true
        env:
          CI: true
