name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform: [windows-latest]
        node-version: [18.x]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: deps
        run: npm ci
      - name: build
        run: npx cmake-js rebuild -D
      - name: test
        run: npm test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
         gcov: true
         verbose: true
        env:
          CI: true
